{{- if .Values.rbac.create -}}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "collectorset-controller.fullname" . }}-collector
  labels:
    {{- include "collectorset-controller.labels" . | nindent 4}}
  annotations:
    {{- include "collectorset-controller.annotations" . | nindent 4}}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        logicmonitor.com/aggregate-to-collector: "true"
rules: [ ] # The control plane automatically fills in the rules
---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ include "collectorset-controller.fullname" . }}-collector-child
  labels:
    logicmonitor.com/aggregate-to-collector: "true"
    {{- include "collectorset-controller.labels" . | nindent 4}}
  annotations:
    {{- include "collectorset-controller.annotations" . | nindent 4}}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - containers
      - nodes
      - nodes/proxy
      - nodes/metrics
      - componentstatuses
      - replicasets
      - persistentvolumes
      - persistentvolumeclaims
      - ingresses
      - services
      - endpoints
      - pods/log
      - events
      - configmaps
    verbs:
      - list
      - get
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - get
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - deployments
    verbs:
      - list
      - get
  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
      # - networkpolicies
    verbs:
      - list
      - get
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - list
      - get
  - nonResourceURLs:
      - /
      - /healthz
      - /healthz/*
      - /metrics
      - /proxy
    verbs:
      - get
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "collectorset-controller.fullname" . }}-collector
  labels:
      {{- include "collectorset-controller.labels" . | nindent 4}}
  annotations:
    {{- include "collectorset-controller.annotations" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "collectorset-controller.fullname" . }}-collector
subjects:
  - kind: ServiceAccount
    name: {{ include "collectorset-controller.serviceAccountName" . }}-collector
    namespace: {{ template "collectorset-controller.namespace" . }}
{{- end -}}
