# dummy cs object to trigger crd creation, by default if no crd object then helm chart ignores crd creation
apiVersion: logicmonitor.com/v1beta1
kind: CollectorSet
metadata:
  name: "dummy-void-cs-{{ .Release.Name }}"
  namespace: {{ include "lmutil.release.namespace" . }}
spec:
  replicas: 0
  clusterName: "dummy-void-cs-{{ .Release.Name }}"

