apiVersion: v2
description: Automated collector management
icon: https://logicmonitor.github.com/k8s-helm-charts/lm_logo.png
kubeVersion: '>= 1.14.0-0'
maintainers:
- email: argus@logicmonitor.com
  name: LogicMonitor
name: collectorset-controller
version: 0.9.0
