## REQUIRED VALUES

# The LogicMonitor API key ID.
accessID: ""
# The LogicMonitor API key.
accessKey: ""
# The LogicMonitor account name.
account: ""
# To enable verbose logging at debug level.
log:
  level: info

## OPTIONAL VALUES

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
rbac:
  create: true
# The public etcd discovery token used to add etcd hosts to the cluster device group.
image:
  registry: ""
  repository: ""
  name: collectorset-controller
  pullPolicy: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
# The Http/s proxy.
proxy:
  url: ""
  user: ""
  pass: ""
# It provides the simplest way to run Pod on particular Node(s) based on labels on the node.
nodeSelector: {}
# It allows you to constrain which nodes your pod is eligible to be scheduled on.
affinity: {}
# The priority class name for Pod priority. If this parameter is set then user must have PriorityClass resource created otherwise Pod will be rejected.
priorityClassName: ""
# tolerations are applied to pods, and allow the pods to schedule onto nodes with matching taints.
tolerations: []
# Labels to apply on all objects created by Collectorset controller
labels: {}
# Annotations to apply on all objects created by Collectorset controller
annotations: {}
# Set flag to ignore ssl/tls validation
ignoreSSL: false

imagePullSecrets: []
global:
  accessID: ""
  accessKey: ""
  account: ""
  collectorsetServiceNameSuffix: ""
  proxy:
    url: ""
    user: ""
    pass: ""
  image:
    registry: ""
    repository: ""
    pullPolicy: Always
  userDefinedSecret: ""
  imagePullSecrets: []

podSecurityContext: {}
securityContext:
  capabilities:
    add: []
    drop: []
probe:
  enabled: true
  grpcContainerProbeEnabled: true
  startup:
    failureThreshold: 3
    periodSeconds: 10
  liveness:
    failureThreshold: 3
    periodSeconds: 10
  readiness:
    failureThreshold: 3
    periodSeconds: 10
