apiVersion: v2
description: Automated Kubernetes monitoring
icon: https://logicmonitor.github.io/helm-charts/lm_logo.png
kubeVersion: '>= 1.16.0-0'
maintainers:
  - email: argus@logicmonitor.com
    name: LogicMonitor
name: argus
version: 4.0.0
home: https://logicmonitor.github.io/helm-charts
appVersion: v9.0.0