apiVersion: v2
description: Automated Kubernetes monitoring
icon: https://logicmonitor.github.io/helm-charts/lm_logo.png
kubeVersion: '>= 1.14.0-0'
maintainers:
- email: argus@logicmonitor.com
  name: LogicMonitor
name: argus
version: 0.18.0