apiVersion: v2
description: A Helm chart for sending k8s logs to Logic Monitor
name: lm-logs
version: 0.8.0
maintainers:
  - email: dev@logicmonitor.com
    name: LogicMonitor
icon: https://logicmonitor.github.io/helm-charts/lm_logo.png
appVersion: 1.4.0
home: https://logicmonitor.github.io/helm-charts
